name: Cross-Platform Tests

on:
  # pull_request:
  #   branches: [ master ]
  schedule:
    - cron: '0 2 * * 1'  # Poniedziałek o 2:00 UTC
  workflow_dispatch:  # Możliwość ręcznego uruchomienia

jobs:
  test:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18.x, 20.x]
      fail-fast: false
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Run tests
      run: npm test
      
    - name: Check for test artifacts
      run: |
        echo "Test results directory:"
        ls -la testresults/ || echo "No testresults directory"
        echo "Coverage directory:"
        ls -la coverage/ || echo "No coverage directory"
      shell: bash